### ISSUE TITLE
Test script improvements and license

### ISSUE THREAD

**Issue by hannob** [dadrian/tldr.fail#3]
I would like to propose a few improvements to the test script: https://gist.github.com/dadrian/f51e7f96aa659937775232cc3576e5f8

* Add a python shebang
* Produce easier to interpret output. Right now it appears the script expects me to manually inspect the server responses. I'd suggest having something like a "this looks good", "some problem appeared" message at the end.

I'd send pull requests, but right now the script is just on a gist and does not even have a license. Would you agree to put the script under some standard opensource license and put it in a proper repo?

**Comment by dadrian** [comment]
I added the LICENSE and put it in the repo. Sorry for the delay, I missed this notification.
